// Code generated by MockGen. DO NOT EDIT.
// Source: etcd2cfg.go
//
// Generated by this command:
//
//	mockgen -source etcd2cfg.go -package mocks -destination mocks/mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	clientv3 "go.etcd.io/etcd/client/v3"
	gomock "go.uber.org/mock/gomock"
)

// MocketcdClientAccessor is a mock of etcdClientAccessor interface.
type MocketcdClientAccessor struct {
	ctrl     *gomock.Controller
	recorder *MocketcdClientAccessorMockRecorder
	isgomock struct{}
}

// MocketcdClientAccessorMockRecorder is the mock recorder for MocketcdClientAccessor.
type MocketcdClientAccessorMockRecorder struct {
	mock *MocketcdClientAccessor
}

// NewMocketcdClientAccessor creates a new mock instance.
func NewMocketcdClientAccessor(ctrl *gomock.Controller) *MocketcdClientAccessor {
	mock := &MocketcdClientAccessor{ctrl: ctrl}
	mock.recorder = &MocketcdClientAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocketcdClientAccessor) EXPECT() *MocketcdClientAccessorMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MocketcdClientAccessor) Delete(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.DeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*clientv3.DeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MocketcdClientAccessorMockRecorder) Delete(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocketcdClientAccessor)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MocketcdClientAccessor) Get(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*clientv3.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocketcdClientAccessorMockRecorder) Get(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocketcdClientAccessor)(nil).Get), varargs...)
}

// Put mocks base method.
func (m *MocketcdClientAccessor) Put(ctx context.Context, key, val string, opts ...clientv3.OpOption) (*clientv3.PutResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, val}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Put", varargs...)
	ret0, _ := ret[0].(*clientv3.PutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MocketcdClientAccessorMockRecorder) Put(ctx, key, val any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, val}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MocketcdClientAccessor)(nil).Put), varargs...)
}
